.TH "/home/runner/work/OPIChat/OPIChat/basic_client Directory Reference" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/OPIChat/OPIChat/basic_client Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbasic_client\&.c\fP"
.br
.ti -1c
.RI "file \fBbasic_client\&.h\fP"
.br
.ti -1c
.RI "file \fBpython_echo\&.py\fP"
.br
.in -1c
