.TH "command_parameter" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
command_parameter \- Structure to store a command parameter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <message\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "void * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure to store a command parameter\&. 


.PP
Definition at line 41 of file message\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* key"

.PP
Definition at line 43 of file message\&.h\&.
.SS "void* value"

.PP
Definition at line 44 of file message\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
