.TH "/home/runner/work/OPIChat/OPIChat/tests/unit_testing/commands_test.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/OPIChat/OPIChat/tests/unit_testing/commands_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <criterion/criterion\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'commands\&.h'\fP
.br
\fC#include 'xalloc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (commands, ping_empty_payload)"
.br
.ti -1c
.RI "\fBTest\fP (commands, ping_with_payload)"
.br
.ti -1c
.RI "\fBTest\fP (commands, dup_true)"
.br
.ti -1c
.RI "\fBTest\fP (commands, dup_false)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Test (commands, dup_false)"

.PP
Definition at line 80 of file commands_test\&.c\&.
.SS "Test (commands, dup_true)"

.PP
Definition at line 59 of file commands_test\&.c\&.
.SS "Test (commands, ping_empty_payload)"

.PP
Definition at line 7 of file commands_test\&.c\&.
.SS "Test (commands, ping_with_payload)"

.PP
Definition at line 33 of file commands_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
