.TH "/home/runner/work/OPIChat/OPIChat/src/server/commands/handle_list_rooms.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/OPIChat/OPIChat/src/server/commands/handle_list_rooms.c
.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'client\&.h'\fP
.br
\fC#include 'commands\&.h'\fP
.br
\fC#include 'message\&.h'\fP
.br
\fC#include 'room\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBlist_of_rooms\fP (struct \fBroom\fP *\fBroom\fP)"
.br
.ti -1c
.RI "struct \fBsend_pool\fP * \fBhandle_list_rooms\fP (struct \fBmessage\fP *msg, struct \fBclient\fP *\fBclient\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBsend_pool\fP* handle_list_rooms (struct \fBmessage\fP * msg, struct \fBclient\fP * client)"

.PP
Definition at line 28 of file handle_list_rooms\&.c\&.
.SS "char* list_of_rooms (struct \fBroom\fP * room)"

.PP
Definition at line 10 of file handle_list_rooms\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
