.TH "/home/runner/work/OPIChat/OPIChat/src/server/commands/handle_create_room.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/OPIChat/OPIChat/src/server/commands/handle_create_room.c
.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'client\&.h'\fP
.br
\fC#include 'commands\&.h'\fP
.br
\fC#include 'message\&.h'\fP
.br
\fC#include 'room\&.h'\fP
.br
\fC#include 'xalloc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBsend_pool\fP * \fBhandle_create_room\fP (struct \fBmessage\fP *msg, struct \fBclient\fP *\fBclient\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBsend_pool\fP* handle_create_room (struct \fBmessage\fP * msg, struct \fBclient\fP * client)"

.PP
Definition at line 11 of file handle_create_room\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
