.TH "/home/runner/work/OPIChat/OPIChat/src/client/init_client_socket.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/OPIChat/OPIChat/src/client/init_client_socket.c
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'init_socket\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsetup_client_socket\fP (const char *\fBip\fP, const char *\fBport\fP)"
.br
.RI "Create a connection socket\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int setup_client_socket (const char * ip, const char * port)"

.PP
Create a connection socket\&. 
.PP
\fBParameters\fP
.RS 4
\fIip\fP The ip to connect to 
.br
\fIport\fP The port to connect on 
.RE
.PP
\fBReturns\fP
.RS 4
The created socket, -1 on error 
.RE
.PP

.PP
Definition at line 28 of file init_client_socket\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
