.TH "/home/runner/work/OPIChat/OPIChat/tests/unit_testing/message_serializer_test.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/OPIChat/OPIChat/tests/unit_testing/message_serializer_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <criterion/criterion\&.h>\fP
.br
\fC#include 'message\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (message_serializing, subject_client_response)"
.br
.ti -1c
.RI "\fBTest\fP (message_serializing, subject_server_notification)"
.br
.ti -1c
.RI "\fBTest\fP (message_serializing, basic_ping)"
.br
.ti -1c
.RI "\fBTest\fP (message_serializing, key_value_is_payload)"
.br
.ti -1c
.RI "\fBTest\fP (message_serializing, multiple_command_parameters)"
.br
.ti -1c
.RI "\fBTest\fP (message_serializing, invalid_size)"
.br
.ti -1c
.RI "\fBTest\fP (message_serializing, empty_message)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Test (message_serializing, basic_ping)"

.PP
Definition at line 28 of file message_serializer_test\&.c\&.
.SS "Test (message_serializing, empty_message)"

.PP
Definition at line 75 of file message_serializer_test\&.c\&.
.SS "Test (message_serializing, invalid_size)"

.PP
Definition at line 62 of file message_serializer_test\&.c\&.
.SS "Test (message_serializing, key_value_is_payload)"

.PP
Definition at line 39 of file message_serializer_test\&.c\&.
.SS "Test (message_serializing, multiple_command_parameters)"

.PP
Definition at line 51 of file message_serializer_test\&.c\&.
.SS "Test (message_serializing, subject_client_response)"

.PP
Definition at line 6 of file message_serializer_test\&.c\&.
.SS "Test (message_serializing, subject_server_notification)"

.PP
Definition at line 17 of file message_serializer_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
