.TH "/home/runner/work/OPIChat/OPIChat/src/common/message/message_init.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/OPIChat/OPIChat/src/common/message/message_init.c
.SH SYNOPSIS
.br
.PP
\fC#include 'message\&.h'\fP
.br
\fC#include 'xalloc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBmessage\fP * \fBinit_message\fP (uint8_t status_code)"
.br
.RI "Initializes a struct message with the param status code affected\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBmessage\fP* init_message (uint8_t status_code)"

.PP
Initializes a struct message with the param status code affected\&. 
.PP
\fBParameters\fP
.RS 4
\fIstatus_code\fP 
.RE
.PP
\fBReturns\fP
.RS 4
struct message* 
.RE
.PP

.PP
Definition at line 4 of file message_init\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
