.TH "/home/runner/work/OPIChat/OPIChat/src/common/message/message_serializer.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/OPIChat/OPIChat/src/common/message/message_serializer.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'message\&.h'\fP
.br
\fC#include 'my_itoa\&.h'\fP
.br
\fC#include 'xalloc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBcompose_message\fP (const struct \fBmessage\fP *\fBmessage\fP)"
.br
.RI "Takes a message struct and serializes it to a string\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* compose_message (const struct \fBmessage\fP * message)"

.PP
Takes a message struct and serializes it to a string\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP The message as a message struct
.RE
.PP
\fBReturns\fP
.RS 4
char pointer 
.RE
.PP

.PP
Definition at line 41 of file message_serializer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
