.TH "/home/runner/work/OPIChat/OPIChat/src/common/utils/my_itoa.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/OPIChat/OPIChat/src/common/utils/my_itoa.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBswap\fP (char *a, char *b)"
.br
.RI "Swaps two char*\&. "
.ti -1c
.RI "void \fBreverse\fP (char str[], int len)"
.br
.RI "Reverses a string\&. "
.ti -1c
.RI "char * \fBmy_itoa\fP (int value, char *s)"
.br
.RI "Converts an int into a string\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_itoa (int value, char * s)"

.PP
Converts an int into a string\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP 
.br
\fIs\fP 
.RE
.PP
\fBReturns\fP
.RS 4
char* 
.RE
.PP

.PP
Definition at line 20 of file my_itoa\&.c\&.
.SS "void reverse (char str[], int len)"

.PP
Reverses a string\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP 
.br
\fIlen\fP 
.RE
.PP

.PP
Definition at line 8 of file my_itoa\&.c\&.
.SS "void swap (char * a, char * b)"

.PP
Swaps two char*\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP 
.br
\fIb\fP 
.RE
.PP

.PP
Definition at line 1 of file my_itoa\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
