.TH "room" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
room
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <room\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBowner_socket\fP"
.br
.ti -1c
.RI "size_t \fBnb_clients\fP"
.br
.ti -1c
.RI "int * \fBclients_sockets\fP"
.br
.ti -1c
.RI "struct \fBroom\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file room\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int* clients_sockets"

.PP
Definition at line 30 of file room\&.h\&.
.SS "char* name"

.PP
Definition at line 26 of file room\&.h\&.
.SS "size_t nb_clients"

.PP
Definition at line 29 of file room\&.h\&.
.SS "struct \fBroom\fP* next"

.PP
Definition at line 32 of file room\&.h\&.
.SS "int owner_socket"

.PP
Definition at line 27 of file room\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
