.TH "/home/runner/work/OPIChat/OPIChat/tests/unit_testing/safe_io_test.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/OPIChat/OPIChat/tests/unit_testing/safe_io_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <criterion/criterion\&.h>\fP
.br
\fC#include <criterion/redirect\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'client_read\&.h'\fP
.br
\fC#include 'init_socket\&.h'\fP
.br
\fC#include 'logger\&.h'\fP
.br
\fC#include 'message\&.h'\fP
.br
\fC#include 'safe_io\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (safe_io, \fBsafe_write\fP,\&.init=cr_redirect_stdout)"
.br
.ti -1c
.RI "\fBTest\fP (safe_io, \fBsafe_read\fP)"
.br
.ti -1c
.RI "\fBTest\fP (safe_io, safe_send_recv)"
.br
.ti -1c
.RI "\fBTest\fP (safe_io, safe_recv__slow_loris_hack)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Test (safe_io, \fBsafe_read\fP)"

.PP
Definition at line 27 of file safe_io_test\&.c\&.
.SS "Test (safe_io, safe_recv__slow_loris_hack)"

.PP
Definition at line 88 of file safe_io_test\&.c\&.
.SS "Test (safe_io, safe_send_recv)"

.PP
Definition at line 50 of file safe_io_test\&.c\&.
.SS "Test (safe_io, \fBsafe_write\fP, \&. init = \fCcr_redirect_stdout\fP)"

.PP
Definition at line 16 of file safe_io_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
