.TH "/home/runner/work/OPIChat/OPIChat/include/type_check.h" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/OPIChat/OPIChat/include/type_check.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBcheck_is_number\fP (const char *s)"
.br
.RI "Check if a string is a number\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool check_is_number (const char * s)"

.PP
Check if a string is a number\&. 
.PP
\fBParameters\fP
.RS 4
\fIs\fP The string to check 
.RE
.PP
\fBReturns\fP
.RS 4
true if the string is a number, false otherwise 
.RE
.PP

.PP
Definition at line 5 of file type_check\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
