.TH "src/server/commands Directory Reference" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/server/commands Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhandle_broadcast\&.c\fP"
.br
.ti -1c
.RI "file \fBhandle_create_room\&.c\fP"
.br
.ti -1c
.RI "file \fBhandle_delete_room\&.c\fP"
.br
.ti -1c
.RI "file \fBhandle_join_room\&.c\fP"
.br
.ti -1c
.RI "file \fBhandle_leave_room\&.c\fP"
.br
.ti -1c
.RI "file \fBhandle_list_rooms\&.c\fP"
.br
.ti -1c
.RI "file \fBhandle_list_users\&.c\fP"
.br
.ti -1c
.RI "file \fBhandle_login\&.c\fP"
.br
.ti -1c
.RI "file \fBhandle_ping\&.c\fP"
.br
.ti -1c
.RI "file \fBhandle_profile\&.c\fP"
.br
.ti -1c
.RI "file \fBhandle_send_dm\&.c\fP"
.br
.ti -1c
.RI "file \fBhandle_send_room\&.c\fP"
.br
.in -1c
