.TH "src/common/message Directory Reference" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/common/message Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmessage_command_parameters\&.c\fP"
.br
.ti -1c
.RI "file \fBmessage_free\&.c\fP"
.br
.ti -1c
.RI "file \fBmessage_init\&.c\fP"
.br
.ti -1c
.RI "file \fBmessage_parser\&.c\fP"
.br
.ti -1c
.RI "file \fBmessage_serializer\&.c\fP"
.br
.in -1c
