.TH "src/client Directory Reference" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/client Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinit_client_socket\&.c\fP"
.br
.ti -1c
.RI "file \fBread_from_server\&.c\fP"
.br
.ti -1c
.RI "file \fBread_from_stdin\&.c\fP"
.br
.in -1c
