.TH "src/common Directory Reference" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/common Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmessage\fP"
.br
.ti -1c
.RI "directory \fButils\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsafe_io\&.c\fP"
.br
.in -1c
