.TH "include/client_read.h" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/client_read.h
.SH SYNOPSIS
.br
.PP
\fC#include <netdb\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBread_thread\fP (void *socket)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void * read_thread (void * socket)"

.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
