.TH "tests/unit_testing/client_test.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/unit_testing/client_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <criterion/criterion\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include 'client\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (\fBclient\fP, add_client__remove_client)"
.br
.ti -1c
.RI "\fBTest\fP (\fBclient\fP, \fBfind_client\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Test (\fBclient\fP, add_client__remove_client)"

.PP
Definition at line \fB8\fP of file \fBclient_test\&.c\fP\&.
.SS "Test (\fBclient\fP, \fBfind_client\fP)"

.PP
Definition at line \fB39\fP of file \fBclient_test\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
