.TH "include/client.h" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/client.h
.SH SYNOPSIS
.br
.PP
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBclient\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBget_client_ip\fP (struct \fBclient\fP *\fBclient\fP)"
.br
.RI "Get the client IPv4/IPv6 address\&. "
.ti -1c
.RI "struct \fBclient\fP * \fBadd_client\fP (struct \fBclient\fP *\fBclient\fP, int client_socket, struct sockaddr sockaddr, socklen_t sockaddr_len)"
.br
.RI "Add a new client client to the linked list connection\&. "
.ti -1c
.RI "struct \fBclient\fP * \fBremove_client\fP (struct \fBclient\fP *connection, int client_socket)"
.br
.RI "Remove the client client from the linked list connection\&. "
.ti -1c
.RI "struct \fBclient\fP * \fBfind_client\fP (struct \fBclient\fP *connection, int client_socket)"
.br
.RI "Find the client element where the socket is equal to client sock\&. "
.ti -1c
.RI "struct \fBclient\fP * \fBfind_client_by_username\fP (struct \fBclient\fP *\fBclient\fP, char *username)"
.br
.RI "Find the first client who match the username\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBclient\fP * \fBclients\fP"
.br
.RI "Contain all the information about all clients (linked list) "
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBclient\fP * add_client (struct \fBclient\fP * client, int client_socket, struct sockaddr sockaddr, socklen_t sockaddr_len)"

.PP
Add a new client client to the linked list connection\&. 
.PP
\fBParameters\fP
.RS 4
\fIconnection\fP The client linked list with all the clients
.br
\fIclient_socket\fP The client socket fd to add
.br
\fIsockaddr\fP The client socket address info (used to get the client ip)
.br
\fIsockaddr_len\fP The client socket address info length
.RE
.PP
\fBReturns\fP
.RS 4
The client linked list with the element added
.RE
.PP
Add the new client element with a head insert 
.PP
Definition at line \fB37\fP of file \fBclient\&.c\fP\&.
.SS "struct \fBclient\fP * find_client (struct \fBclient\fP * connection, int client_socket)"

.PP
Find the client element where the socket is equal to client sock\&. 
.PP
\fBParameters\fP
.RS 4
\fIconnection\fP The client linked list with all the clients
.br
\fIclient_socket\fP The client socket to find
.RE
.PP
\fBReturns\fP
.RS 4
The client element of the specific client
.RE
.PP
Iterate over the linked list until it finds the client\&. If the client is not in the linked list returns NULL 
.PP
Definition at line \fB90\fP of file \fBclient\&.c\fP\&.
.SS "struct \fBclient\fP * find_client_by_username (struct \fBclient\fP * client, char * username)"

.PP
Find the first client who match the username\&. 
.PP
\fBParameters\fP
.RS 4
\fIconnection\fP The client linked list with all the clients
.br
\fIusername\fP The username to find
.RE
.PP
\fBReturns\fP
.RS 4
The client element of the specific client 
.RE
.PP

.PP
Definition at line \fB98\fP of file \fBclient\&.c\fP\&.
.SS "char * get_client_ip (struct \fBclient\fP * client)"

.PP
Get the client IPv4/IPv6 address\&. 
.PP
\fBWarning\fP
.RS 4
This function returns dynamically allocated string and thus must be freed after use
.RE
.PP
\fBParameters\fP
.RS 4
\fIclient\fP The client 
.RE
.PP
\fBReturns\fP
.RS 4
char* The client IPv4/IPv6 address (x\&.x\&.x\&.x or x:x:x:x:x:x:x:x) 
.RE
.PP

.PP
Definition at line \fB16\fP of file \fBclient\&.c\fP\&.
.SS "struct \fBclient\fP * remove_client (struct \fBclient\fP * connection, int client_socket)"

.PP
Remove the client client from the linked list connection\&. 
.PP
\fBParameters\fP
.RS 4
\fIconnection\fP The client linked list with all the clients
.br
\fIclient_socket\fP The client socket fd to remove
.RE
.PP
\fBReturns\fP
.RS 4
The client linked list with element removed
.RE
.PP
Iterate over the linked list to find the right client and remove it 
.PP
Definition at line \fB68\fP of file \fBclient\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBclient\fP* clients"

.PP
Contain all the information about all clients (linked list) 
.PP
Definition at line \fB12\fP of file \fBclient\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
