.TH "src/client_main.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/client_main.c
.SH SYNOPSIS
.br
.PP
\fC#include <errno\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'init_socket\&.h'\fP
.br
\fC#include 'logger\&.h'\fP
.br
\fC#include 'read_from_server\&.h'\fP
.br
\fC#include 'read_from_stdin\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBserver_socket\fP"
.br
.ti -1c
.RI "char * \fBip\fP"
.br
.ti -1c
.RI "char * \fBport\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB14\fP of file \fBclient_main\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char* ip\fC [extern]\fP"

.PP
Definition at line \fB11\fP of file \fBinit_socket\&.h\fP\&.
.SS "char* port\fC [extern]\fP"

.PP
Definition at line \fB12\fP of file \fBinit_socket\&.h\fP\&.
.SS "int server_socket\fC [extern]\fP"

.PP
Definition at line \fB10\fP of file \fBinit_socket\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
