.TH "client" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBclient_socket\fP"
.br
.ti -1c
.RI "struct sockaddr_storage * \fBclient_sockaddr\fP"
.br
.ti -1c
.RI "char * \fBip\fP"
.br
.ti -1c
.RI "char * \fBusername\fP"
.br
.ti -1c
.RI "size_t \fBnb_rooms\fP"
.br
.ti -1c
.RI "char ** \fBrooms\fP"
.br
.ti -1c
.RI "struct \fBclient\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBclient\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "struct sockaddr_storage* client_sockaddr"

.PP
Definition at line \fB17\fP of file \fBclient\&.h\fP\&.
.SS "int client_socket"

.PP
Definition at line \fB16\fP of file \fBclient\&.h\fP\&.
.SS "char* ip"

.PP
Definition at line \fB18\fP of file \fBclient\&.h\fP\&.
.SS "size_t nb_rooms"

.PP
Definition at line \fB22\fP of file \fBclient\&.h\fP\&.
.SS "struct \fBclient\fP* next"

.PP
Definition at line \fB25\fP of file \fBclient\&.h\fP\&.
.SS "char** rooms"

.PP
Definition at line \fB23\fP of file \fBclient\&.h\fP\&.
.SS "char* username"

.PP
Definition at line \fB20\fP of file \fBclient\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
