.TH "command_parameters" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
command_parameters
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBcommand\fP"
.br
.ti -1c
.RI "uint8_t \fBnb_parameters\fP"
.br
.ti -1c
.RI "char ** \fBparameters_name\fP"
.br
.ti -1c
.RI "bool \fBloop_payload\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBread_from_stdin\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "char* command"

.PP
Definition at line \fB21\fP of file \fBread_from_stdin\&.c\fP\&.
.SS "bool loop_payload"

.PP
Definition at line \fB24\fP of file \fBread_from_stdin\&.c\fP\&.
.SS "uint8_t nb_parameters"

.PP
Definition at line \fB22\fP of file \fBread_from_stdin\&.c\fP\&.
.SS "char** parameters_name"

.PP
Definition at line \fB23\fP of file \fBread_from_stdin\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
