.TH "epoll_server/connection.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
epoll_server/connection.c
.SH SYNOPSIS
.br
.PP
\fC#include 'connection\&.h'\fP
.br
\fC#include <err\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'utils/xalloc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBconnection_t\fP * \fBadd_client\fP (struct \fBconnection_t\fP *connection, int client_socket)"
.br
.RI "Add a new client \fBconnection_t\fP to the linked list connection\&. "
.ti -1c
.RI "struct \fBconnection_t\fP * \fBremove_client\fP (struct \fBconnection_t\fP *connection, int client_socket)"
.br
.RI "Remove the client \fBconnection_t\fP from the linked list connection\&. "
.ti -1c
.RI "struct \fBconnection_t\fP * \fBfind_client\fP (struct \fBconnection_t\fP *connection, int client_socket)"
.br
.RI "Find the \fBconnection_t\fP element where the socket is equal to client sock\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBconnection_t\fP * add_client (struct \fBconnection_t\fP * connection, int client_socket)"

.PP
Add a new client \fBconnection_t\fP to the linked list connection\&. 
.PP
\fBParameters\fP
.RS 4
\fIconnection\fP the \fBconnection_t\fP linked list with all the clients
.br
\fIclient_socket\fP the client socket fd to add
.RE
.PP
\fBReturns\fP
.RS 4
The \fBconnection_t\fP linked list with the element added
.RE
.PP
Add the new \fBconnection_t\fP element with a head insert 
.PP
Definition at line \fB9\fP of file \fBconnection\&.c\fP\&.
.SS "struct \fBconnection_t\fP * find_client (struct \fBconnection_t\fP * connection, int client_socket)"

.PP
Find the \fBconnection_t\fP element where the socket is equal to client sock\&. 
.PP
\fBParameters\fP
.RS 4
\fIconnection\fP the \fBconnection_t\fP linked list with all the clients
.br
\fIclient_socket\fP the client socket to find
.RE
.PP
\fBReturns\fP
.RS 4
The \fBconnection_t\fP element of the specific client
.RE
.PP
Iterate over the linked list until it finds the \fBconnection_t\fP\&. If the client is not in the linked list returns NULL 
.PP
Definition at line \fB54\fP of file \fBconnection\&.c\fP\&.
.SS "struct \fBconnection_t\fP * remove_client (struct \fBconnection_t\fP * connection, int client_socket)"

.PP
Remove the client \fBconnection_t\fP from the linked list connection\&. 
.PP
\fBParameters\fP
.RS 4
\fIconnection\fP the \fBconnection_t\fP linked list with all the clients
.br
\fIclient_socket\fP the client socket fd to remove
.RE
.PP
\fBReturns\fP
.RS 4
The \fBconnection_t\fP linked list with element removed
.RE
.PP
Iterate over the linked list to find the right \fBconnection_t\fP and remove it 
.PP
Definition at line \fB22\fP of file \fBconnection\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
