.TH "epoll_server/epoll-server.h" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
epoll_server/epoll-server.h
.SH SYNOPSIS
.br
.PP
\fC#include <netdb\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include 'connection\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_EVENTS\fP   64"
.br
.RI "The length of the event array, must be greater than zero\&. "
.ti -1c
.RI "#define \fBDEFAULT_BUFFER_SIZE\fP   2048"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcreate_and_bind\fP (struct addrinfo *addrinfo)"
.br
.RI "Iterate over the struct addrinfo elements to create and bind a socket\&. "
.ti -1c
.RI "int \fBprepare_socket\fP (const char *\fBip\fP, const char *\fBport\fP)"
.br
.RI "Initialize the Addrinfo struct and call create_and bind() and listen(2) "
.ti -1c
.RI "struct \fBconnection_t\fP * \fBaccept_client\fP (int \fBepoll_instance\fP, int \fBserver_socket\fP, struct \fBconnection_t\fP *connection)"
.br
.RI "Accept a new client and add it to the \fBconnection_t\fP struct\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULT_BUFFER_SIZE   2048"

.PP
Definition at line \fB15\fP of file \fBepoll\-server\&.h\fP\&.
.SS "#define MAX_EVENTS   64"

.PP
The length of the event array, must be greater than zero\&. 
.PP
Definition at line \fB13\fP of file \fBepoll\-server\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "struct \fBconnection_t\fP * accept_client (int epoll_instance, int server_socket, struct \fBconnection_t\fP * connection)"

.PP
Accept a new client and add it to the \fBconnection_t\fP struct\&. 
.PP
\fBParameters\fP
.RS 4
\fIepoll_instance\fP the epoll instance 
.br
\fIserver_socket\fP listening socket 
.br
\fIconnection\fP the connection linked list with all the current connections
.RE
.PP
\fBReturns\fP
.RS 4
The connection struct with the new client added 
.RE
.PP

.PP
Definition at line \fB57\fP of file \fBepoll\-server\&.c\fP\&.
.SS "int create_and_bind (struct addrinfo * addrinfo)"

.PP
Iterate over the struct addrinfo elements to create and bind a socket\&. 
.PP
\fBParameters\fP
.RS 4
\fIaddrinfo\fP struct addrinfo elements
.RE
.PP
\fBReturns\fP
.RS 4
The created socket or exit with 1 if there is an error
.RE
.PP
Try to create and connect a socket with every addrinfo element until it succeeds 
.PP
Definition at line \fB10\fP of file \fBbasic_server\&.c\fP\&.
.SS "int prepare_socket (const char * ip, const char * port)"

.PP
Initialize the Addrinfo struct and call create_and bind() and listen(2) 
.PP
\fBParameters\fP
.RS 4
\fIip\fP IP address of the server 
.br
\fIport\fP Port of the server
.RE
.PP
\fBReturns\fP
.RS 4
The created socket
.RE
.PP
Initialize the struct addrinfo needed by \fBcreate_and_bind()\fP before calling it\&. When \fBcreate_and_bind()\fP returns a valid socket, set the socket to listening and return it\&.
.PP
Initialize the Addrinfo struct and call create_and bind() and listen(2)
.PP
Initialize the addrinfo struct and call create_and bind() and listen(2)
.PP
\fBParameters\fP
.RS 4
\fIip\fP IP address of the server 
.br
\fIport\fP Port of the server
.RE
.PP
\fBReturns\fP
.RS 4
The created socket 
.RE
.PP

.PP
Definition at line \fB30\fP of file \fBbasic_client\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
