.TH "epoll_server/epoll-server.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
epoll_server/epoll-server.c
.SH SYNOPSIS
.br
.PP
\fC#include 'epoll\-server\&.h'\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/epoll\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include 'utils/xalloc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_CONNECTION_NB\fP   5"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcreate_and_bind\fP (struct addrinfo *addrinfo)"
.br
.RI "Iterate over the struct addrinfo elements to create and bind a socket\&. "
.ti -1c
.RI "int \fBprepare_socket\fP (const char *\fBip\fP, const char *\fBport\fP)"
.br
.RI "Initialize the addrinfo struct and call \fBcreate_and_connect()\fP "
.ti -1c
.RI "struct \fBconnection_t\fP * \fBaccept_client\fP (int \fBepoll_instance\fP, int \fBserver_socket\fP, struct \fBconnection_t\fP *connection)"
.br
.RI "Accept a new client and add it to the \fBconnection_t\fP struct\&. "
.ti -1c
.RI "struct \fBconnection_t\fP * \fBdelete_epoll_client\fP (struct \fBconnection_t\fP *connection, int \fBepoll_instance\fP, int client_socket)"
.br
.ti -1c
.RI "struct \fBconnection_t\fP * \fBcommunicate\fP (int \fBepoll_instance\fP, int client_socket, struct \fBconnection_t\fP *connections)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_CONNECTION_NB   5"

.PP
Definition at line \fB14\fP of file \fBepoll\-server\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "struct \fBconnection_t\fP * accept_client (int epoll_instance, int server_socket, struct \fBconnection_t\fP * connection)"

.PP
Accept a new client and add it to the \fBconnection_t\fP struct\&. 
.PP
\fBParameters\fP
.RS 4
\fIepoll_instance\fP the epoll instance 
.br
\fIserver_socket\fP listening socket 
.br
\fIconnection\fP the connection linked list with all the current connections
.RE
.PP
\fBReturns\fP
.RS 4
The connection struct with the new client added 
.RE
.PP

.PP
Definition at line \fB57\fP of file \fBepoll\-server\&.c\fP\&.
.SS "struct \fBconnection_t\fP * communicate (int epoll_instance, int client_socket, struct \fBconnection_t\fP * connections)"

.PP
Definition at line \fB89\fP of file \fBepoll\-server\&.c\fP\&.
.SS "int create_and_bind (struct addrinfo * addrinfo)"

.PP
Iterate over the struct addrinfo elements to create and bind a socket\&. 
.PP
\fBParameters\fP
.RS 4
\fIaddrinfo\fP struct addrinfo elements
.RE
.PP
\fBReturns\fP
.RS 4
The created socket or exit with 1 if there is an error
.RE
.PP
Try to create and connect a socket with every addrinfo element until it succeeds 
.PP
Definition at line \fB16\fP of file \fBepoll\-server\&.c\fP\&.
.SS "struct \fBconnection_t\fP * delete_epoll_client (struct \fBconnection_t\fP * connection, int epoll_instance, int client_socket)"

.PP
Definition at line \fB77\fP of file \fBepoll\-server\&.c\fP\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB159\fP of file \fBepoll\-server\&.c\fP\&.
.SS "int prepare_socket (const char * ip, const char * port)"

.PP
Initialize the addrinfo struct and call \fBcreate_and_connect()\fP Initialize the Addrinfo struct and call create_and bind() and listen(2)
.PP
Initialize the addrinfo struct and call create_and bind() and listen(2)
.PP
\fBParameters\fP
.RS 4
\fIip\fP IP address of the server 
.br
\fIport\fP Port of the server
.RE
.PP
\fBReturns\fP
.RS 4
The created socket 
.RE
.PP

.PP
Definition at line \fB37\fP of file \fBepoll\-server\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
