.TH "src/server/commands/handle_list_users.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/server/commands/handle_list_users.c
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'client\&.h'\fP
.br
\fC#include 'commands\&.h'\fP
.br
\fC#include 'message\&.h'\fP
.br
\fC#include 'xalloc\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBlist_of_users\fP (struct \fBclient\fP *\fBclient\fP)"
.br
.ti -1c
.RI "struct \fBsend_pool\fP * \fBhandle_list_users\fP (struct \fBmessage\fP *msg, struct \fBclient\fP *\fBclient\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBsend_pool\fP * handle_list_users (struct \fBmessage\fP * msg, struct \fBclient\fP * client)"

.PP
Definition at line \fB29\fP of file \fBhandle_list_users\&.c\fP\&.
.SS "char * list_of_users (struct \fBclient\fP * client)"

.PP
Definition at line \fB9\fP of file \fBhandle_list_users\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
