.TH "src/server/epoll/init_server_socket.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/server/epoll/init_server_socket.c
.SH SYNOPSIS
.br
.PP
\fC#include <netdb\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'init_socket\&.h'\fP
.br
\fC#include 'logger\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsetup_server_socket\fP (const char *\fBip\fP, const char *\fBport\fP)"
.br
.RI "Create a listening socket\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int setup_server_socket (const char * ip, const char * port)"

.PP
Create a listening socket\&. 
.PP
\fBParameters\fP
.RS 4
\fIip\fP The ip to listen on 
.br
\fIport\fP The port to listen on 
.RE
.PP
\fBReturns\fP
.RS 4
The created socket, exit on error 
.RE
.PP

.PP
Definition at line \fB38\fP of file \fBinit_server_socket\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
