.TH "include/init_socket.h" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/init_socket.h
.SH SYNOPSIS
.br
.PP
\fC#include <netdb\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBACKLOG\fP   16"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsetup_server_socket\fP (const char *\fBip\fP, const char *\fBport\fP)"
.br
.RI "Create a listening socket\&. "
.ti -1c
.RI "int \fBsetup_client_socket\fP (const char *\fBip\fP, const char *\fBport\fP)"
.br
.RI "Create a connection socket\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBserver_socket\fP"
.br
.ti -1c
.RI "char * \fBip\fP"
.br
.ti -1c
.RI "char * \fBport\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BACKLOG   16"

.PP
Definition at line \fB8\fP of file \fBinit_socket\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int setup_client_socket (const char * ip, const char * port)"

.PP
Create a connection socket\&. 
.PP
\fBParameters\fP
.RS 4
\fIip\fP The ip to connect to 
.br
\fIport\fP The port to connect on 
.RE
.PP
\fBReturns\fP
.RS 4
The created socket, -1 on error 
.RE
.PP

.PP
Definition at line \fB28\fP of file \fBinit_client_socket\&.c\fP\&.
.SS "int setup_server_socket (const char * ip, const char * port)"

.PP
Create a listening socket\&. 
.PP
\fBParameters\fP
.RS 4
\fIip\fP The ip to listen on 
.br
\fIport\fP The port to listen on 
.RE
.PP
\fBReturns\fP
.RS 4
The created socket, exit on error 
.RE
.PP

.PP
Definition at line \fB38\fP of file \fBinit_server_socket\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "char* ip"

.PP
Definition at line \fB11\fP of file \fBinit_socket\&.h\fP\&.
.SS "char* port"

.PP
Definition at line \fB12\fP of file \fBinit_socket\&.h\fP\&.
.SS "int server_socket"

.PP
Definition at line \fB10\fP of file \fBinit_socket\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
