.TH "tests/unit_testing/message_serializer_test.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/unit_testing/message_serializer_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <criterion/criterion\&.h>\fP
.br
\fC#include 'message\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (message_serializing, subject_client_response)"
.br
.ti -1c
.RI "\fBTest\fP (message_serializing, subject_server_notification)"
.br
.ti -1c
.RI "\fBTest\fP (message_serializing, basic_ping)"
.br
.ti -1c
.RI "\fBTest\fP (message_serializing, key_value_is_payload)"
.br
.ti -1c
.RI "\fBTest\fP (message_serializing, multiple_command_parameters)"
.br
.ti -1c
.RI "\fBTest\fP (message_serializing, invalid_size)"
.br
.ti -1c
.RI "\fBTest\fP (message_serializing, empty_message)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Test (message_serializing, basic_ping)"

.PP
Definition at line \fB28\fP of file \fBmessage_serializer_test\&.c\fP\&.
.SS "Test (message_serializing, empty_message)"

.PP
Definition at line \fB75\fP of file \fBmessage_serializer_test\&.c\fP\&.
.SS "Test (message_serializing, invalid_size)"

.PP
Definition at line \fB62\fP of file \fBmessage_serializer_test\&.c\fP\&.
.SS "Test (message_serializing, key_value_is_payload)"

.PP
Definition at line \fB39\fP of file \fBmessage_serializer_test\&.c\fP\&.
.SS "Test (message_serializing, multiple_command_parameters)"

.PP
Definition at line \fB51\fP of file \fBmessage_serializer_test\&.c\fP\&.
.SS "Test (message_serializing, subject_client_response)"

.PP
Definition at line \fB6\fP of file \fBmessage_serializer_test\&.c\fP\&.
.SS "Test (message_serializing, subject_server_notification)"

.PP
Definition at line \fB17\fP of file \fBmessage_serializer_test\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
