.TH "python_echo" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
python_echo
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def python_echo\&.main (void)"

.PP
Definition at line \fB7\fP of file \fBpython_echo\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
