.TH "include/read_from_server.h" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/read_from_server.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBread_from_server_thread\fP (void *none)"
.br
.RI "Reads from the server and print (eventually) the formated message\&. This function is thread compliant\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void * read_from_server_thread (void * none)"

.PP
Reads from the server and print (eventually) the formated message\&. This function is thread compliant\&. 
.PP
Definition at line \fB16\fP of file \fBread_from_server\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
