.TH "tests/unit_testing/room_test.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/unit_testing/room_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <criterion/criterion\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include 'room\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (\fBroom\fP, \fBadd_room\fP)"
.br
.ti -1c
.RI "\fBTest\fP (\fBroom\fP, add_room_non_alphanumeric)"
.br
.ti -1c
.RI "\fBTest\fP (\fBroom\fP, add_room_duplicate)"
.br
.ti -1c
.RI "\fBTest\fP (\fBroom\fP, \fBfind_room\fP)"
.br
.ti -1c
.RI "\fBTest\fP (\fBroom\fP, find_room_no_found)"
.br
.ti -1c
.RI "\fBTest\fP (\fBroom\fP, \fBremove_room\fP)"
.br
.ti -1c
.RI "\fBTest\fP (\fBroom\fP, remove_room_no_found)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Test (\fBroom\fP, \fBadd_room\fP)"

.PP
Definition at line \fB9\fP of file \fBroom_test\&.c\fP\&.
.SS "Test (\fBroom\fP, add_room_duplicate)"

.PP
Definition at line \fB47\fP of file \fBroom_test\&.c\fP\&.
.SS "Test (\fBroom\fP, add_room_non_alphanumeric)"

.PP
Definition at line \fB37\fP of file \fBroom_test\&.c\fP\&.
.SS "Test (\fBroom\fP, \fBfind_room\fP)"

.PP
Definition at line \fB62\fP of file \fBroom_test\&.c\fP\&.
.SS "Test (\fBroom\fP, find_room_no_found)"

.PP
Definition at line \fB86\fP of file \fBroom_test\&.c\fP\&.
.SS "Test (\fBroom\fP, \fBremove_room\fP)"

.PP
Definition at line \fB104\fP of file \fBroom_test\&.c\fP\&.
.SS "Test (\fBroom\fP, remove_room_no_found)"

.PP
Definition at line \fB124\fP of file \fBroom_test\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
