.TH "safe_recv_data" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
safe_recv_data
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsockfd\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "char * \fBrecv_buffer\fP"
.br
.ti -1c
.RI "time_t \fBstarting_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB78\fP of file \fBsafe_io\&.c\fP\&.
.SH "Field Documentation"
.PP 
.SS "int flags"

.PP
Definition at line \fB81\fP of file \fBsafe_io\&.c\fP\&.
.SS "char* recv_buffer"

.PP
Definition at line \fB82\fP of file \fBsafe_io\&.c\fP\&.
.SS "int sockfd"

.PP
Definition at line \fB80\fP of file \fBsafe_io\&.c\fP\&.
.SS "time_t starting_time"

.PP
Definition at line \fB83\fP of file \fBsafe_io\&.c\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
