.TH "send_pool" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
send_pool
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <commands\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBnb_msg\fP"
.br
.ti -1c
.RI "int * \fBclients_sockets\fP"
.br
.ti -1c
.RI "struct \fBmessage\fP ** \fBmsg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBcommands\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int* clients_sockets"

.PP
Definition at line \fB11\fP of file \fBcommands\&.h\fP\&.
.SS "struct \fBmessage\fP** msg"

.PP
Definition at line \fB12\fP of file \fBcommands\&.h\fP\&.
.SS "uint8_t nb_msg"

.PP
Definition at line \fB10\fP of file \fBcommands\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
