.TH "tests/test_main.c" 3 "Wed Feb 9 2022" "OPIchat" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/test_main.c
.SH SYNOPSIS
.br
.PP
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'client\&.h'\fP
.br
\fC#include 'client_read\&.h'\fP
.br
\fC#include 'commands\&.h'\fP
.br
\fC#include 'init_socket\&.h'\fP
.br
\fC#include 'message\&.h'\fP
.br
\fC#include 'read_from_stdin\&.h'\fP
.br
\fC#include 'safe_io\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line \fB17\fP of file \fBtest_main\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPIchat from the source code\&.
