# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.3
        with:
          # Path to Doxyfile
          doxyfile-path: ./docs/Doxyfile.conf # default is ./Doxyfile
          # Working directory
          working-directory: . # default is ./docs
      - name: Github commit and push
        # You may pin to the exact commit or the version.
        # uses: Smart-Transportation/push@c77535fe7a94645f7ceca83e48e6cc977620710e
        uses: Smart-Transportation/push@v1.3
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token:  ${{ secrets.GITHUB_TOKEN }}
          # Commit message.
          message: Documentation generated.
