name: Run test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_testing:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install criterion
      run: sudo apt-get install libcriterion-dev
    - name: make check
      run: make check
