name: Run test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_testing:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Downloading criterion package
      uses: actions/download-artifact@v1
      with:
        name: criterion
        version: "{{ github.event.pull_request.head.repo.name }}"
        url: "https://github.com/Snaipe/Criterion/releases/download/v2.3.3/criterion-v2.3.3-linux-x86_64.tar.bz2"
        path: "/tmp/criterion-v2.3.3-linux-x86_64.tar.bz2"
    
    - name: Install criterion
      run:
        mkdir -p /tmp/criterion-v2.3.3-linux-x86_64
        tar -xjf /tmp/criterion-v2.3.3-linux-x86_64.tar.bz2 -C /tmp/criterion-v2.3.3-linux-x86_64
        cp /tmp/criterion-v2.3.3-linux-x86_64/bin/criterion /usr/local/bin/
    - name: make check
      run: make check
